package com.changr.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "jobs")
public class Job extends BaseEntity {

    public static Job createFromProject(Project p)
    {
        Job j = new Job();
        //j.setStatus(JobStatus.PENDING);
        j.setProjectId(p.getId());
        j.setUser(p.getUser());
        return j;
    }

    private String id;
    private String projectId;
    //private Project project;
    private String user;
    private String status;
    private String output;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute
    public String getProjectId() { return projectId; }
    public void setProjectId(String p) { projectId = p; }

    /*
    @NotNull
    @DynamoDBAttribute(attributeName = "project")
    public Project getProject() { return project; }
    public void setProject(Project p) { project = p; }
    */

    @DynamoDBAttribute
    public String getUser() { return user; }
    public void setUser(String u) { user = u; }

    @DynamoDBAttribute
    public String getStatus() { return status; }
    public void setStatus(String s) { status = s; }

    @DynamoDBAttribute
    public String getOutput() { return output; }
    public void setOutput(String o) { output = o; }


}
