package com.changr.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import javax.validation.constraints.NotNull;
import java.io.Serializable;

@DynamoDBTable(tableName = "jobs")
public class Job implements Serializable {

    public static Job createFromProject(Project p)
    {
        Job j = new Job();
        j.setProjectId(p.getId());
        j.setUserId(p.getUser());
        return j;
    }

    private String id;
    private String projectId;
    //private Project project;
    private String userId;
    private String status;
    private String output;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBAttribute
    public String getProjectId() { return projectId; }
    public void setProjectId(String p) { projectId = p; }

    /*
    @NotNull
    @DynamoDBAttribute(attributeName = "project")
    public Project getProject() { return project; }
    public void setProject(Project p) { project = p; }
    */

    @DynamoDBAttribute
    public String getUserId() { return userId; }
    public void setUserId(String u) { userId = u; }

    @DynamoDBAttribute
    public String getStatus() { return status; }
    public void setStatus(String s) { status = s; }

    @DynamoDBAttribute
    public String getOutput() { return output; }
    public void setOutput(String o) { output = o; }

}
