package com.changr.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "projects")
public class Project {

    private String id;
    private String user;
    private String name;

    public static Project create(String id, String user, String name)
    {
        Project p = new Project();
        p.id = id;
        p.user = user;
        p.name = name;
        return p;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute(attributeName = "user")
    public String getUser() {
        return user;
    }
    public void setUser(String u) {
        user = u;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }
    public void setName(String n) {
        name = n;
    }

/*
    @DynamoDBAttribute
    public String getContent() {
        return content;
    }
*/
}
